vars: { d2-config: { layout-engine: elk } }
Schema: {
'pipeline/exams.pickle'
'pipeline/classifications.pickle'
}
QuestionsMeta: {
'pipeline/questions_meta.pickle'
}
Schema.'pipeline/exams.pickle' -> QuestionsMeta: changes
Schema.'pipeline/classifications.pickle' -> QuestionsMeta: changes
QuestionsMain: {
'pipeline/questions_main.pickle'
}
QuestionsMeta.'pipeline/questions_meta.pickle' -> QuestionsMain: changes
Questions: {
'pipeline/questions.pickle'
}
QuestionsMeta.'pipeline/questions_meta.pickle' -> Questions: changes
QuestionsMain.'pipeline/questions_main.pickle' -> Questions: changes
QuestionCounts: {
'pipeline/question_counts.html'
'pipeline/question_counts.json'
}
Questions.'pipeline/questions.pickle' -> QuestionCounts: changes
QuestionsJSON: {
'pipeline/questions.json'
}
Questions.'pipeline/questions.pickle' -> QuestionsJSON: changes
FrontendData: {
'pipeline/frontend_data.js'
}
Questions.'pipeline/questions.pickle' -> FrontendData: changes
Schema.'pipeline/exams.pickle' -> FrontendData: changes
Schema.'pipeline/classifications.pickle' -> FrontendData: changes
QuestionCounts.'pipeline/question_counts.json' -> FrontendData: changes
Index: {
'html/index.html'
}
'template_html/index.html' -> Index: changes
