vars: { d2-config: { layout-engine: elk } }
Schema: {
'exams.pickle'
'classifications.pickle'
}
QuestionsMeta: {
'questions_meta.pickle'
}
Schema.'exams.pickle' -> QuestionsMeta: changes
Schema.'classifications.pickle' -> QuestionsMeta: changes
QuestionsMain: {
'questions_main.pickle'
}
QuestionsMeta.'questions_meta.pickle' -> QuestionsMain: changes
Questions: {
'questions.pickle'
}
QuestionsMeta.'questions_meta.pickle' -> Questions: changes
QuestionsMain.'questions_main.pickle' -> Questions: changes
QuestionCounts: {
'question_counts.html'
'question_counts.json'
}
Questions.'questions.pickle' -> QuestionCounts: changes
QuestionsJSON: {
'questions.json'
}
Questions.'questions.pickle' -> QuestionsJSON: changes
FrontendData: {
'frontend_data.js'
}
Questions.'questions.pickle' -> FrontendData: changes
Schema.'exams.pickle' -> FrontendData: changes
Schema.'classifications.pickle' -> FrontendData: changes
QuestionCounts.'question_counts.json' -> FrontendData: changes
Index: {
'index.html'
}
'template_html/index.html' -> Index: changes
