vars: {
  d2-config: {
    layout-engine: elk
  }
}

direction: down

Schema: {
  "exams.pickle"
  "classifications.pickle"
}


QuestionsMeta: {
  "questions_meta.pickle"
}
QuestionsMeta -> Schema."exams.pickle": require
QuestionsMeta -> Schema."classifications.pickle": require


QuestionsMain: {
  "questions_main.pickle"
}
QuestionsMain -> QuestionsMeta."questions_meta.pickle": require


Questions: {
  "questions.pickle"
}
Questions -> QuestionsMeta."questions_meta.pickle": require
Questions -> QuestionsMain."questions_main.pickle": require


QuestionCounts: {
  "question_counts.html"
  "question_counts.json"
}
QuestionCounts -> Questions."questions.pickle": require


QuestionsJSON: {
  "questions.json"
}
QuestionsJSON -> Questions."questions.pickle": require


"models.py"


FrontendData: {
  "frontend_data.js"
}
FrontendData -> Questions."questions.pickle": require
FrontendData -> Schema."exams.pickle": require
FrontendData -> Schema."classifications.pickle": require
FrontendData -> QuestionCounts."question_counts.json": require
FrontendData -> "models.py": require

"html_templates/index.html"

Index: {
  "html/index.html"
}
Index."html/index.html" -> "html_templates/index.html": require
